### ISSUE TITLE
Foundry default setting for Token Disposition is not honored when creating new actors

### ISSUE THREAD

**Issue by iamrpgdm** [Muttley/foundryvtt-shadowdark#163]
You can set the default Foundry Token settings and the Token disposition setting is not what the prototype token gets set to upon actor creation.

**Comment by bakbakbakbakbak** [comment]
@Muttley is this related to the manipulation of tokens on drop you worked on?

**Comment by Muttley** [comment]
No, that's a good point.

The issue is that Foundry's defaults are limited as in they're for *all* tokens, but really you may want different settings for different types of Actors.

I think we should comment this out now and maybe add system settings that can be used to override the Foundry defaults if needed.

**Comment by bakbakbakbakbak** [comment]
Yeah, we can always do this explicitly for a `actor.type === "Player"` and `actor.type === "NPC"` situation IF a system settings wants that?
