### ISSUE TITLE
Feature: Indicate monster attack specials in the chat card

### ISSUE THREAD

**Issue by chmking** [Muttley/foundryvtt-shadowdark#320]
The attack description does a great job of listing the special, (e.g. 1d4 + Acid)
![Screenshot 2023-04-12 073544](https://user-images.githubusercontent.com/12450799/231475311-346bcae1-3868-498a-9ff0-a671abdf6cec.png)

But the chat card doesn't have a mention of the special
![Screenshot 2023-04-12 073631](https://user-images.githubusercontent.com/12450799/231475418-e11062dd-0cda-48f6-b228-cffa857436c1.png)

Listing the special here might help remind GM's to apply the special on attacks.

**Comment by gatesvp** [comment]
Looking at this right now. It's looks like the "special" value is not being carried into the roll dialog. So by the time the Data Card is ready to render, the "special" feature is already gone.

Question to consider for final output.

Right now, the input value for "special" is an ability name. For example, Gelatinous Cube has a "Touch" attack that causes "Toxin". That "Toxin" has its own special text that isn't necessarily visible to the Players because its in the monster's abilities. I can see three approaches for how we render this:

1. **Render the Word "Toxin"**. This is purely reminder text. It doesn't reveal anything to the players, it's mostly a reminder for the GM.
2. **Render the feature text**: Simply "name/description". So you would see `Toxin: DC 15 CON or paralyzed 1d4 rounds.`
3. **Carry the feature**: As with two, but I'm not limited to passing Name/Description. We can carry the whole item for any future automation.

**Comment by gatesvp** [comment]
> My current strategy is to implement 3, but display it as 2

PR#454 now implements this.

I think we can do better with the feature, but not until we have luck, targeting and action resolution implemented.
