### ISSUE TITLE
Feature: Add support for non-numerical values for attackBonus & damageBonus fields

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#337]
Some spells and effects, and perhaps a GM who wants to homebrew; will require variable bonuses to items, such as a dice formulation `2d4`.

**Comment by git-steve-git** [comment]
In a similar vein, we need support for variable number of attacks.  For example, the Ten-Eyed Oracle has an attack block with "1d4 eye rays"  (personally, I'd be content with the ability to write the string in the field, I can handle actually rolling separately.)

**Comment by Muttley** [comment]
> In a similar vein, we need support for variable number of attacks. For example, the Ten-Eyed Oracle has an attack block with "2d4 eyestalk rays" (personally, I'd be content with the ability to write the string in the field, I can handle actually rolling separately.)

To be honest, that would be best handled by the GM typing `/r 2d4` in the chat box or using dice tray.  No point building something like that in really.

**Comment by Muttley** [comment]
I think we should ditch the 3 separate settings for the damage dice:

![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/853835/22ee1d24-b991-4427-b2ec-31c0403df296)

Instead we should convert it to a single free text dice formula string, it would need an upgrade script which builds the new string from existing attacks for people, which is trivial enough.

**Comment by git-steve-git** [comment]
> To be honest, that would be best handled by the GM typing `/r 2d4` in the chat box or using dice tray. No point building something like that in really.

I'm not suggesting we support functionality to roll the number of attacks from the character sheet.  Only that we support the ability to input a string rather than a number, so that attacks like this can be properly input for display purposes.  Right now we can't indicate that the monster even has this variable number of attacks, unless we stick it on the description or something, which is out of the way and easily missed.

I don't believe the numerical value we input now has any functionality connected to it anyway (please correct me if I'm wrong), so I don't think this would break anything.
