### ISSUE TITLE
Feature(dice): Advantage parsing due to Talents

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#38]
**Why?**
Some talents give advantage on rolls, such as:
- HP rolls
- Spellcasting Checks (Magic Missile)

**How?**
Introducing something like this in the DataModel could be read from the Dice mechanics and apply advantage automatically:
```js
{
  system: {
    talents: {
      advantage: ["hp", "spellcast"],
      weaponMastery: ["whip"; "bastardSword", "longbow"],
      meleeAttackBonus: 4,
      meleeDamageBonus: 2,
      rangedAttackBonus: 1,
      rangedDamageBonus: 2,
      spellcastingCheckBonus: 3
    },
  },
}
```

This should be implemented in conjunction with #34 .

**Comment by Muttley** [comment]
Seems a reasonable approach.  This should be on the Player Actor class.

There's at least one spell that wizards always have advantage on too (Magic Missile), but that's not talent related.  Maybe instead off calling this dataset `system.talents` a more generic `system.bonuses` would be better.

I do prefer the idea of tracking weapon mastery by name rather than a flag in the Weapon Item, as if a player lost their weapon for whatever reason, they'd need to remember to re-enable it when they got it back.

I'd probably use a slugified version of the item name for the key for simplicity (otherwise people could alter the capitalisation on an item and lose mastery ;)).  In cause you're not aware, I discovered the other day that Foundry has a built in slugify method on the string primitive which is handy.
