### ISSUE TITLE
Inventory header disappearing on large inventory

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#438]
When a large amount of items are added to the inventory, and the user scrolls down, the header is not sticky to the top, making it hard to read:

Before scrolling:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/105067023/3ca27084-a0ce-4a91-9cc5-2a87aff28150)

After scrolling:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/105067023/c3dea532-c539-4e38-a34b-3b7f2d98a310)

**Comment by gatesvp** [comment]
So I did some quick research on this. That scroll bar on the right is not for the tab, but for any tab that causes an overflow on this pop-up. You can see it on the Notes tab as well if you do small resize.

I'm looking at the table for the inventory and it lacks a distinct Header/Body/Footer in the table itself. So the CSS can't really "sticky" the header because we don't call it a header. I have a fix on my machine that makes an explicit header and tweaks the CSS.

There's one extra wrinkle that I'm seeing. The "Total Coins" and "Total Gems" kind of look like Footers that should also be sticky. So I'll create PR under this assumption.

**Comment by Muttley** [comment]
Fixed in new UI overhaul
