### ISSUE TITLE
[BUG] Unnecessary "items not found" warning for "+2 Stats Points" from ShadowDarklings

### ISSUE THREAD

**Issue by johncarney** [Muttley/foundryvtt-shadowdark#894]
When importing a character that rolled the "_+2 points to distribute to any stats_" talent from *ShadowDarklings*, the importer shows a "_items not found_" and presents a "_partially import_" button. This is even though the character has two corresponding "+1 to [ability]" talents in the JSON. This could lead to potential confusion.

It's debatable whether this is a problem in _ShadowDarklings_ or in the _Shadowdark_ Foundry game system, but I would argue that _ShadowDarklings_ is properly representing what was rolled and the importer should either simply ignore "+2 Stats Points" items in the JSON, or (ideally) check that there are the correct number of corresponding "+1 to [ability]" items before presenting a warning.

# Example JSON

[Snubrogg.json](https://github.com/user-attachments/files/16949998/Snubrogg.json)

# Screenshots

Note that 14 was rolled for CHA.

<img width="448" alt="partially-import" src="https://github.com/user-attachments/assets/eecc6207-62bf-4eab-9747-e40e6a77b0a7">
<img width="596" alt="snubrogg-abilities" src="https://github.com/user-attachments/assets/e290062d-ec00-4094-b9e9-e15a00769a4a">
<img width="596" alt="snubrogg-talents" src="https://github.com/user-attachments/assets/b19b4cf8-878b-402f-b95f-e9c0ce096ee9">

**Comment by PrototypeESBU** [comment]
Thanks for pointing this out and including the JSON file. The underlying issues is that Shadowdarkling records the result of each talent rolls as well as the stat assignments. Normally these roll records get filtered out, but this is case it was just an outlier that was missed. As you suspected, it's a harmless bug as the talents will still get added correctly based on the rest of the data in the JSON. We'll get this fixed in the next patch.
