### ISSUE TITLE
Shadowdark Actor HP Default Settings Bug

### ISSUE THREAD

**Issue by domcoder** [Muttley/foundryvtt-shadowdark#904]
Foundry Version: v12 (stable) Build 331
Shadowdark Version: v3.1.3
Active Modules: None

Newly created actors's tokens fail to default to Core Game 'Default Token Configuration' Bar 1 for attribute.hp.

When dragging from the compendium of Shadowdark, default token settings have been set to show name, AC and HP on hover. However, the token only shows name and AC.

![image](https://github.com/user-attachments/assets/f56aa3c9-03b9-4f9b-896d-8bd64267c956)
![image](https://github.com/user-attachments/assets/89ddc029-db09-4529-a8c3-7e77dcee0ce8)

This happens only (as far as I've tested) when the default Bar 1 Attribute is attributes.hp. 

Whatever is in Bar 2 Attribute works fine - when Default Token Configuration Bar 2 Attribute is attributes.hp, it works! Except the hp bar is no longer green - it goes from light blue to dark blue. I've only just started using foundry, but I would imagine that this part is design as expected.
Manual editing of the actors is a temporary workaround.

**Comment by PrototypeESBU** [comment]
This issue seems limited to "When dragging from the compendium of Shadowdark". Creating monsters via the imported seems to work. It's unclear if this is a foundry issue or something in the system, but I'll take a look.

Not sure if you are the same person from this reddit post, but you can check out my suggestions there. https://www.reddit.com/r/FoundryVTT/comments/1frdrud/comment/lpcse57/

**Comment by Muttley** [comment]
I've just done some testing with the 5e system, and it appears single value attributes are never shown on the token in that too, which makes me think this might be a Foundry issue.

**Comment by Muttley** [comment]
Closing as this is a Foundry issue and not anything to do with the system.
